Repository codingBottle/Helfy-SERVER, pull requests merged in 2023-11, with the labels that each got.

#27 Slack 로그백 추가 및 로깅
  build.gradle
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/logback-spring.xml
  module-core/src/main/java/com/codingbottle/common/config/SecurityConfig.java
  module-core/src/main/java/com/codingbottle/common/security/entry/CustomAccessDeniedHandler.java
  module-core/src/main/java/com/codingbottle/common/security/entry/CustomAuthenticationEntryPoint.java
  module-core/src/main/java/com/codingbottle/common/security/filter/FirebaseTokenFilter.java
Labels: Feat, Chore

#32 날씨 API 구현 및 API 연동
  module-api/build.gradle
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/main/java/com/codingbottle/common/config/RedisConfig.java
  module-api/src/main/java/com/codingbottle/common/config/SchedulingConfig.java
  module-api/src/main/java/com/codingbottle/common/config/WebClientConfig.java
  module-api/src/main/java/com/codingbottle/common/redis/RedisService.java
  module-api/src/main/java/com/codingbottle/domain/region/controller/RegionController.java
  module-api/src/main/java/com/codingbottle/domain/user/model/UserResponse.java
  module-api/src/main/java/com/codingbottle/domain/weather/controller/WeatherController.java
  module-api/src/main/java/com/codingbottle/domain/weather/model/CurrentWeatherRequest.java
  module-api/src/main/java/com/codingbottle/domain/weather/model/WeatherResponse.java
  module-api/src/main/java/com/codingbottle/domain/weather/service/WeatherService.java
  module-api/src/main/resources/application.yml
  module-api/src/test/java/com/codingbottle/domain/weather/controller/WeatherControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/weather/service/WeatherServiceTest.java
  module-core/src/main/java/com/codingbottle/domain/region/entity/Region.java
  module-core/src/main/java/com/codingbottle/domain/weather/entity/WeatherCode.java
Labels: Docs, Feat, Chore

#31 게시판 API 구현
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/main/java/com/codingbottle/domain/image/controller/ImageController.java
  module-api/src/main/java/com/codingbottle/domain/image/model/ImageResponse.java
  module-api/src/main/java/com/codingbottle/domain/image/service/ImageService.java
  module-api/src/main/java/com/codingbottle/domain/post/controller/PostController.java
  module-api/src/main/java/com/codingbottle/domain/post/dto/PostRequest.java
  module-api/src/main/java/com/codingbottle/domain/post/dto/PostResponse.java
  module-api/src/main/java/com/codingbottle/domain/post/service/PostService.java
  module-api/src/test/java/com/codingbottle/docs/util/RestDocsTest.java
  module-api/src/test/java/com/codingbottle/domain/image/controller/ImageControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/post/controller/PostControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/post/service/PostServiceTest.java
  module-api/src/test/java/com/codingbottle/fixture/DomainFixture.java
  module-core/src/main/java/com/codingbottle/auth/entity/User.java
  module-core/src/main/java/com/codingbottle/common/config/JpaConfig.java
  module-core/src/main/java/com/codingbottle/common/entity/ObjectTime.java
  module-core/src/main/java/com/codingbottle/common/exception/ApplicationErrorType.java
  module-core/src/main/java/com/codingbottle/domain/image/entity/Directory.java
  module-core/src/main/java/com/codingbottle/domain/image/entity/Image.java
  module-core/src/main/java/com/codingbottle/domain/image/repo/ImageRepository.java
  module-core/src/main/java/com/codingbottle/domain/post/entity/Post.java
  module-core/src/main/java/com/codingbottle/domain/post/repo/PostRepository.java
Labels: Feat

#39 로깅 전략 수정
  module-core/src/main/java/com/codingbottle/common/security/filter/FirebaseTokenFilter.java
Labels: Feat

#40 랜덤 퀴즈 조회 API 구성
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/main/java/com/codingbottle/domain/post/controller/PostController.java
  module-api/src/main/java/com/codingbottle/domain/post/model/PostRequest.java
  module-api/src/main/java/com/codingbottle/domain/post/model/PostResponse.java
  module-api/src/main/java/com/codingbottle/domain/post/service/PostService.java
  module-api/src/main/java/com/codingbottle/domain/quiz/controller/QuizController.java
  module-api/src/main/java/com/codingbottle/domain/quiz/controller/UserQuizController.java
  module-api/src/main/java/com/codingbottle/domain/quiz/model/Type.java
  module-api/src/main/java/com/codingbottle/domain/quiz/service/QuizService.java
  module-api/src/main/java/com/codingbottle/domain/quiz/service/UserQuizService.java
  module-api/src/test/java/com/codingbottle/domain/post/controller/PostControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/quiz/controller/QuizControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/quiz/controller/UserQuizControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/quiz/service/QuizServiceTest.java
  module-api/src/test/java/com/codingbottle/domain/quiz/service/UserQuizServiceTest.java
  module-api/src/test/java/com/codingbottle/fixture/DomainFixture.java
  module-core/build.gradle
  module-core/src/main/java/com/codingbottle/auth/entity/User.java
  module-core/src/main/java/com/codingbottle/common/config/QueryDslConfig.java
  module-core/src/main/java/com/codingbottle/common/entity/BaseEntity.java
  module-core/src/main/java/com/codingbottle/common/exception/ApplicationErrorType.java
  module-core/src/main/java/com/codingbottle/domain/image/entity/Image.java
  module-core/src/main/java/com/codingbottle/domain/post/entity/Post.java
  module-core/src/main/java/com/codingbottle/domain/quiz/entity/Quiz.java
  module-core/src/main/java/com/codingbottle/domain/quiz/entity/QuizStatus.java
  module-core/src/main/java/com/codingbottle/domain/quiz/entity/QuizType.java
  module-core/src/main/java/com/codingbottle/domain/quiz/entity/UserQuiz.java
  module-core/src/main/java/com/codingbottle/domain/quiz/repo/QuizQueryRepository.java
  module-core/src/main/java/com/codingbottle/domain/quiz/repo/QuizSimpleJPARepository.java
  module-core/src/main/java/com/codingbottle/domain/quiz/repo/UserQuizQueryRepository.java
  module-core/src/main/java/com/codingbottle/domain/quiz/repo/UserQuizSimpleJPARepository.java
  module-core/src/test/java/com/codingbottle/CoreApplicationTest.java
  module-core/src/test/java/com/codingbottle/common/annotation/RepositoryTest.java
  module-core/src/test/java/com/codingbottle/common/config/TestQueryDslConfig.java
  module-core/src/test/java/com/codingbottle/domain/quiz/repo/QuizQueryRepositoryTest.java
  module-core/src/test/java/com/codingbottle/domain/quiz/repo/UserQuizQueryRepositoryTest.java
  module-core/src/test/java/com/codingbottle/fixture/CoreDomainFixture.java
  module-core/src/test/resources/application.yml
Labels: Feat, Chore

#41 OpenWeatherMap API 요청시 발생하는 예외 처리
  module-api/src/main/java/com/codingbottle/common/config/WebClientConfig.java
  module-api/src/main/java/com/codingbottle/domain/weather/service/WeatherService.java
  module-core/src/main/java/com/codingbottle/common/exception/ApplicationErrorType.java
Labels: Bug, Feat

#44 사용자 닉네임 변경
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/docs/asciidoc/게시물-API.adoc
  module-api/src/docs/asciidoc/날씨-API.adoc
  module-api/src/docs/asciidoc/사용자-정보-수정-API.adoc
  module-api/src/docs/asciidoc/오류-응답.adoc
  module-api/src/docs/asciidoc/이미지-API.adoc
  module-api/src/docs/asciidoc/지역-API.adoc
  module-api/src/docs/asciidoc/카테고리-API.adoc
  module-api/src/docs/asciidoc/퀴즈-API.adoc
  module-api/src/main/java/com/codingbottle/domain/user/controller/UserController.java
  module-api/src/main/java/com/codingbottle/domain/user/model/UserNicknameRequest.java
  module-api/src/main/java/com/codingbottle/domain/user/service/UserService.java
  module-api/src/test/java/com/codingbottle/domain/user/controller/UserControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/user/service/UserServiceTest.java
  module-api/src/test/java/com/codingbottle/fixture/DomainFixture.java
  module-core/src/main/java/com/codingbottle/auth/entity/User.java
Labels: Docs, Feat

#45 정보 제공 API 구현
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/docs/asciidoc/메인-정보-API.adoc
  module-api/src/main/java/com/codingbottle/domain/information/controller/InformationController.java
  module-api/src/main/java/com/codingbottle/domain/information/service/InformationService.java
  module-api/src/test/java/com/codingbottle/domain/information/controller/InformationControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/information/service/InformationServiceTest.java
  module-api/src/test/java/com/codingbottle/fixture/DomainFixture.java
  module-core/src/main/java/com/codingbottle/domain/information/entity/Information.java
  module-core/src/main/java/com/codingbottle/domain/information/repo/InformationRepository.java
Labels: Feat

#52 LogBack Tool Discord로 변경
  build.gradle
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/logback-spring.xml
Labels: Feat, Refactor

#48 좋아요 api 구현
  module-api/src/docs/asciidoc/게시물-API.adoc
  module-api/src/main/java/com/codingbottle/common/config/RedisConfig.java
  module-api/src/main/java/com/codingbottle/common/redis/LikesRedisService.java
  module-api/src/main/java/com/codingbottle/common/redis/WeatherRedisService.java
  module-api/src/main/java/com/codingbottle/domain/post/controller/PostController.java
  module-api/src/main/java/com/codingbottle/domain/post/model/PostResponse.java
  module-api/src/main/java/com/codingbottle/domain/post/service/PostService.java
  module-api/src/main/java/com/codingbottle/domain/post/service/UserPostLikesService.java
  module-api/src/main/java/com/codingbottle/domain/weather/service/WeatherService.java
  module-api/src/test/java/com/codingbottle/domain/post/controller/PostControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/post/service/PostServiceTest.java
  module-api/src/test/java/com/codingbottle/domain/weather/service/WeatherServiceTest.java
  module-core/src/main/java/com/codingbottle/common/exception/ApplicationErrorType.java
  module-core/src/main/java/com/codingbottle/domain/post/entity/Post.java
  module-core/src/main/java/com/codingbottle/domain/post/entity/UserPostLikes.java
  module-core/src/main/java/com/codingbottle/domain/post/repo/UserPostLikesRepository.java
Labels: Feat

#50 사용자 정보 조회 API
  module-api/build.gradle
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/docs/asciidoc/사용자-정보-조회-API.adoc
  module-api/src/main/java/com/codingbottle/domain/user/controller/UserController.java
  module-api/src/main/java/com/codingbottle/domain/user/model/UserResponse.java
  module-api/src/test/java/com/codingbottle/common/security/WithAuthUser.java
  module-api/src/test/java/com/codingbottle/common/security/WithAuthUserSecurityContextFactory.java
  module-api/src/test/java/com/codingbottle/domain/region/controller/RegionControllerTest.java
  module-api/src/test/java/com/codingbottle/domain/user/controller/UserControllerTest.java
  module-api/src/test/java/com/codingbottle/fixture/DomainFixture.java
Labels: Feat

#56 게시글 삭제시 좋아요가 삭제되지 않는 오류 해결 (#56)
  module-api/src/main/java/com/codingbottle/domain/post/service/PostService.java
  module-api/src/test/java/com/codingbottle/domain/post/service/PostServiceTest.java
  module-core/src/main/java/com/codingbottle/common/exception/ApplicationErrorType.java
Labels: Bug

#57 게시글 삭제 테스트 오류 해결
  module-api/src/test/java/com/codingbottle/domain/post/service/PostServiceTest.java
Labels: Bug
